import os

from dotenv import load_dotenv
from hindsight_client import Hindsight

load_dotenv()

HINDSIGHT_API_KEY = os.getenv("HINDSIGHT_API_KEY")

BANK_ID = "threatmemory"
BASE_URL = "https://api.hindsight.vectorize.io"


CASES = [
    # =========================================================
    # VPN / REMOTE ACCESS — FALSE ALARMS
    # =========================================================

    """
    Security case: Repeated failed logins from 185.20.4.7.
    User: admin@company.com.
    25 failed authentication attempts occurred around 03:10 AM.
    Investigation confirmed that 185.20.4.7 is part of the company's
    corporate VPN infrastructure. The employee was working remotely.
    Analyst verdict: FALSE ALARM.
    Action: Verify VPN ownership and employee location before blocking.
    """,

    """
    Security case: 19 failed login attempts from 185.20.4.8.
    User: finance@company.com.
    Activity occurred outside normal working hours.
    Network investigation showed the source IP belonged to the
    corporate VPN address range. The employee was traveling and
    connected through the company VPN.
    Analyst verdict: FALSE ALARM.
    Action: Check VPN logs and user travel information.
    """,

    """
    Security case: 31 failed authentication attempts from 185.20.4.12.
    User: engineering@company.com.
    The IP initially appeared suspicious because of the unusual hour.
    Security operations confirmed the address was assigned to the
    corporate remote-access VPN.
    Analyst verdict: FALSE ALARM.
    Action: Confirm VPN assignment before escalating.
    """,

    """
    Security case: 14 failed login attempts from 185.20.4.15.
    User: hr@company.com.
    Login activity occurred at 02:40 AM.
    The source address was confirmed as an internal VPN gateway.
    The employee was working remotely.
    Analyst verdict: FALSE ALARM.
    Action: Verify the source against the current VPN IP inventory.
    """,

    # =========================================================
    # BACKUP JOBS — FALSE ALARMS
    # =========================================================

    """
    Security case: 210 GB outbound transfer detected at 02:05 AM.
    Source host: backup-server-01.
    Destination: company cloud backup storage.
    Investigation showed the transfer was generated by the scheduled
    nightly backup process.
    Analyst verdict: FALSE ALARM.
    Action: Verify scheduled backup jobs before escalating large transfers.
    """,

    """
    Security case: 175 GB data transfer occurred at 01:55 AM.
    Source: backup-server-02.
    Destination: approved corporate backup storage.
    The process matched the organization's automated backup schedule.
    Analyst verdict: FALSE ALARM.
    Action: Compare the transfer with backup-job schedules.
    """,

    """
    Security case: 240 GB outbound network transfer from backup-server-03.
    Activity started shortly after midnight.
    The destination was an approved cloud backup account and the
    process was the normal scheduled backup task.
    Analyst verdict: FALSE ALARM.
    Action: Validate destination ownership and backup schedule.
    """,

    # =========================================================
    # BUSINESS TRAVEL — FALSE ALARMS
    # =========================================================

    """
    Security case: Successful login detected from Singapore for
    employee@company.com.
    The country was new for the account and the login occurred
    outside the user's normal hours.
    HR records and travel information confirmed that the employee
    was attending a business conference in Singapore.
    Analyst verdict: FALSE ALARM.
    Action: Check approved travel records before escalating new-country logins.
    """,

    """
    Security case: User account logged in from Germany for the first time.
    Device and location were initially unfamiliar.
    The employee was confirmed to be traveling for a customer meeting.
    Analyst verdict: FALSE ALARM.
    Action: Verify travel itinerary and device information.
    """,

    """
    Security case: New-country login from the United Kingdom for
    sales@company.com.
    The alert was generated because the account normally logs in from India.
    Investigation confirmed the employee was on an approved business trip.
    Analyst verdict: FALSE ALARM.
    Action: Cross-check travel records before disabling the account.
    """,

    # =========================================================
    # REAL ATTACKS — CREDENTIAL STUFFING
    # =========================================================

    """
    Security case: Credential stuffing attack detected.
    More than 400 employee accounts received failed login attempts
    within eight minutes.
    Attempts originated from 37 previously unseen external IP addresses.
    Several accounts later received successful logins.
    Analyst verdict: REAL THREAT.
    Action: Block malicious infrastructure, force credential resets,
    review compromised accounts, and enforce MFA.
    """,

    """
    Security case: 180 user accounts were targeted by automated
    login attempts from multiple unrelated external IP addresses.
    Attack frequency was highly abnormal and several accounts were
    successfully accessed after repeated failures.
    Analyst verdict: REAL THREAT.
    Action: Investigate account compromise and initiate credential resets.
    """,

    """
    Security case: Large burst of authentication failures targeted
    privileged administrator accounts.
    Source addresses were unknown external systems and showed no
    relationship to company VPN infrastructure.
    Analyst verdict: REAL THREAT.
    Action: Protect privileged accounts, investigate source IPs,
    and review successful authentications.
    """,

    # =========================================================
    # REAL ATTACKS — DATA EXFILTRATION
    # =========================================================

    """
    Security case: Sensitive customer database was transferred to an
    unknown external storage endpoint.
    The transfer occurred outside approved backup schedules and the
    destination was not present in the company's asset inventory.
    Analyst verdict: REAL THREAT.
    Action: Isolate the affected host and investigate potential data leakage.
    """,

    """
    Security case: A workstation uploaded a large volume of confidential
    documents to an unknown external domain.
    The activity was not associated with any approved business process.
    Endpoint investigation identified an unauthorized process performing
    the transfer.
    Analyst verdict: REAL THREAT.
    Action: Isolate the endpoint and investigate the unauthorized process.
    """,

    # =========================================================
    # ANALYST OVERRIDES
    # =========================================================

    """
    Security case: AI initially classified repeated administrator login
    failures as a likely false alarm because the source appeared similar
    to known VPN traffic.
    Human analyst checked network records and discovered the source IP
    was NOT assigned to the corporate VPN.
    Analyst override: REAL THREAT.
    Action: Escalate the incident and investigate the external source.
    """,

    """
    Security case: AI recommended investigating a large overnight data
    transfer.
    Human analyst reviewed the server and confirmed the process was an
    approved scheduled backup.
    Analyst override: FALSE ALARM.
    Action: Record the backup server and schedule as known benign context.
    """,

    # =========================================================
    # UNKNOWN → LATER RESOLVED
    # =========================================================

    """
    Security case: New login from an unfamiliar IP generated an alert.
    Initial investigation could not determine whether the source was
    legitimate.
    Later investigation confirmed the IP belonged to a newly deployed
    corporate VPN gateway.
    Final analyst verdict: FALSE ALARM.
    Action: Add the new VPN range to known corporate infrastructure.
    """,

    """
    Security case: Large outbound transfer from a development server
    initially had no matching approved process.
    Investigation was initially inconclusive.
    Later the infrastructure team confirmed the transfer was part of
    a newly deployed disaster-recovery replication job.
    Final analyst verdict: FALSE ALARM.
    Action: Record the approved replication process as known activity.
    """,
]


def main():
    if not HINDSIGHT_API_KEY:
        raise RuntimeError("HINDSIGHT_API_KEY is missing from .env")

    hindsight = Hindsight(
        base_url=BASE_URL,
        api_key=HINDSIGHT_API_KEY,
    )

    # Make sure the bank exists.
    try:
        hindsight.create_bank(
            bank_id=BANK_ID,
            name="ThreatMemory Security Cases",
        )
    except Exception:
        pass

    print(f"Seeding {len(CASES)} security cases into Hindsight...")

    for index, case in enumerate(CASES, start=1):
        hindsight.retain(
            bank_id=BANK_ID,
            content=case.strip(),
        )

        print(f"  ✓ Case {index}/{len(CASES)} stored")

    print()
    print("✅ ThreatMemory seed complete.")
    print(f"✅ {len(CASES)} historical security cases stored in Hindsight.")


if __name__ == "__main__":
    main()